services:
  ai-model-training:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
    user: "claude"
